### ISSUE TITLE
Capture output folder by dljc

### ISSUE THREAD

**Issue by langkymus** [aas-integration/integration-test2#1]
Currently, it is unclear what subfolders the dot files will get placed when running the graph generation tool through dljc. For example, for "dyn4j", there are four separate subfolders (starting with an underscore) in which the dot files will get created, but for "jreactphysics3d", there is only one and it is named differently. Is it possible to capture these in dljc, perhaps based on the build system (e.g., ant vs maven)?

**Comment by tim-mccarthy** [comment]
This appears to be a property of how the graphtools module of dljc feeds info to prog2dfg.jar. It doesn't seem to me that there's an entirely straightforward way to standardize this, because a sufficiently complex project might have many different output directories for submodules.

Would it be sufficient to bundle all of them into a subdirectory of dljc-out (resulting in i.e. "dljc-out/graphtools/_target_classes" for jreactphysics3d and "dljc-out/graphtools/_bin" for dyn4j)?

Or to put it another way, at what level does this information need to be available?

**Comment by martinschaef** [comment]
@langkymus, is this issue resolved? If not, I can do sth on the graphtools module, otherwise please close it.

**Comment by langkymus** [comment]
@tim-mccarthy @martinschaef Right now, I hardcoded the paths in common.py for the dots that I want to analyze (some projects generate multiple subfolders and there are also overlaps). If we don't care about duplicates, then I am fine with putting all the generated dots in the same subfolder (a path that dljc understands).

**Comment by tim-mccarthy** [comment]
Since this is causing the experiment script to break on projects that don't have paths hardcoded:


```
Traceback (most recent call last):
  File "experiment.py", line 29, in <module>
    main()
  File "experiment.py", line 26, in main
    frontend.run(project_list, args, kernel_dir)
  File "/home/ttm/integration-test2/frontend.py", line 121, in run
    check_similarity(project, result_file, kernel_file, args.cluster)
  File "/home/ttm/integration-test2/frontend.py", line 92, in check_similarity
    with open(method_file, "r") as mf:
IOError: [Errno 2] No such file or directory: u'/home/ttm/integration-test2/corpus/boofcv/dljc-out/_classes/methods.txt' 
```

It seems we need to get around to fixing this so they're not hardcoded. If there are paths we don't want to analyze, we could have a blacklist rather than the current whitelist.

I will look into this tomorrow unless @martinschaef wants to claim ownership.

**Comment by martinschaef** [comment]
Added some code to harden, but didn't test it :) Could you check if it makes sense?

**Comment by tim-mccarthy** [comment]
That looks sensible to me.
